server:
  port: 8080

spring:
  application:
    name: EMSApplication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/file-upload-sample?createDatabaseIfNotExist=true
    username: vivek
    password: Vivek@123
  jpa:
    show-sql: true
    properties:
        format_sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect